package by.petrovich.storage.controller.command;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_AUTHORIZATION_PAGE,
	GO_TO_ERROR_PAGE,
	GO_TO_ADMIN_PAGE,
	GO_TO_USER_INFO,
	GO_TO_UPDATE_USER_PAGE,
	GO_TO_ADMIN_USERS_PAGE,
	GO_TO_USERS_PROGRAM,
	GO_TO_CNC_PROGRAM_VIEW,

	CNC_PROGRAM_SAVE,
	AUTHORIZATION,
	REGISTRATION,
	CHANGE_LOCAL,
	USER_UPDATE,
	LOG_OUT,
	SEARCH_BY_CNC_PROGRAM_NAME
	
}
