package by.petrovich.storage.controller.command;

public enum CommandName {
	GO_TO_MAIN_PAGE,
	GO_TO_REGISTRATION_PAGE,
	GO_TO_AUTHORIZATION_PAGE,
	GO_TO_ERROR_PAGE,
	GO_TO_ADMIN_PAGE,
	GO_TO_USER_INFO,
	GO_TO_UPDATE_USER_PAGE,
	GO_TO_ADMIN_USERS_PAGE,
	GO_TO_USERS_PROGRAM,
	GO_TO_CNC_PROGRAM_VIEW,
	GO_TO_CNC_PROGRAM_UPDATE,
	GO_TO_DETAILS,
	GO_TO_CNC_MACHINES,
	GO_TO_DETAIL_UPDATE_PAGE,
	GO_TO_CNC_MACHINE_UPDATE_PAGE,
	GO_TO_DETAILS_CNC_PROGRAMS,

	DETAIL_UPDATE,
	CNC_MACHINE_UPDATE,
	CNC_PROGRAM_SAVE,
	CNC_PROGRAM_UPDATE,
	AUTHORIZATION,
	REGISTRATION,
	CHANGE_LOCAL,
	USER_UPDATE,
	LOG_OUT,
	SEARCH_BY_CNC_PROGRAM_NAME
	
}
